name: jasonjensen
favicon: null
layout_spectrum: 0.9713699433486909
typography_spectrum: 0.7593362934421748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8630940557923168
  lightness: 0.5933271597605199
  saturation: 0.8467089594341815
  rhythmicContrast: 0.07310815807431936
purpose: []
